### ISSUE TITLE
Clicking doesn't work as expected

### ISSUE THREAD

**Issue by steffenmllr** [percyhanna/rquery#11]
Hey there, nice work with rquery. I either found a bug or I'm not really sure if I'm using this right
It's a simple components that has a inner component which has a state

``` js
    it('it should open a dropdown onClick', () => {
        var date      = moment().toDate();
        var callback  = sinon.spy();
        var component = TestUtils.renderIntoDocument(
            <MyComponent
                date={date}
                onChange={callback} />
        );

        // Click the Button -> doesn't work
        $R(component).find('a').ensureClick();
        component = $R(component).findComponent(MyInnerComponent).get(0);
        expect(component.state.open).to.equal(true);

        // Click the Button -> works
        component = TestUtils.findRenderedComponentWithType(component, MyInnerComponent);
        var button = TestUtils.findRenderedDOMComponentWithTag(component, 'a');
        TestUtils.Simulate.click(button);
        expect(component.state.open).to.equal(true);
    });
```

**Comment by percyhanna** [comment]
Hmm, without seeing the code for `MyComponent` and `MyInnerComponent` it's difficult to ascertain what the problem might be. We use the `ensureClick` helper method quite a bit in our test suite without any problems. I'd love to provide more assistance, but I would likely need to see some more code, or maybe a screen sharing session or something.

**Comment by steffenmllr** [comment]
here is the click handler: 
https://gist.github.com/steffenmllr/e9c92cc296d855b0f3d3#file-jwreminder-jsx-L105

here is the wrapping to inject the context: 
https://gist.github.com/steffenmllr/e9c92cc296d855b0f3d3#file-utils-js-L12

and this is the test:
https://gist.github.com/steffenmllr/e9c92cc296d855b0f3d3#file-jwreminderspec-jsx-L35-L52

**Comment by percyhanna** [comment]
So I think the problem lies in `findComponent`. The `findComponent` builds a new `rquery` object that contains the entire tree for any matched components. This is probably building an object of unexpected values. I would debug what the [value of `component` is after calling `.get(0)`](https://gist.github.com/steffenmllr/e9c92cc296d855b0f3d3#file-jwreminderspec-jsx-L45), and see if that is returning the expected component. My guess is that `findComponent` is not providing the expected return value that you want, which is potentially causing the problem.

I think that `findComponent` has some complexity to it that is leftover from some previous iterations of `rquery`. It is creating an `rquery` object with the entire rendered tree (all descendants), even though this should be properly handled by retrieving [all the descendants of the root components](https://github.com/percyhanna/rquery/blob/master/rquery.js#L221) when [creating a new query context](https://github.com/percyhanna/rquery/blob/master/rquery.js#L263).

As mentioned above, if you could confirm that the value of `component` is or is _not_ what you expect it to be, then I think we can proceed from there.

**Comment by steffenmllr** [comment]
Ok I check, it is the expected component is what it should be - an instance of `JwReminder`.
It doesn't trigger the function, I can call the function manually `component.toggle()` - also the `a` tag seems fine when I inspect it.

The weird thing is that I trimmed down the component that it only contained the `<a/>` and the click handler and it still doesn't work - maybe there are some other sideeffects because this here works fine in your tests https://gist.github.com/steffenmllr/149384879cd840463328

I also logged thought the rquery.js and the click handler gets called here with the right element:
https://github.com/percyhanna/rquery/blob/master/rquery.js#L296.

This works btw:

``` js
        TestUtils.Simulate.click($R(component).find('a').get(0));
        component = $R(component).findComponent(JwReminder).get(0);
        expect(component.state.open).to.equal(true);
```

This is some weird bug

**Comment by percyhanna** [comment]
This is definitely a strange bug. One other possibility: could you debug to make sure the [click outside mixin](https://gist.github.com/steffenmllr/e9c92cc296d855b0f3d3#file-jwreminder-jsx-L8) isn't interfering? Since that mixin _could_ theoretically call `handleClickOutside`. Perhaps there's a race condition or that mixin is behaving strangely in the test suite? Just a thought.

**Comment by percyhanna** [comment]
Also, could you try modifying your local `rquery.js` and remove the [`getDOMNode()` call from `simulateEvent`](https://github.com/percyhanna/rquery/blob/master/rquery.js#L298):

e.g.

``` javascript
  rquery.prototype.simulateEvent = function (eventName, eventData) {
    for (var i = 0; i < this.components.length; i++) {
      TestUtils.Simulate[eventName](this.components[i], eventData);
    }

    return this;
  };
```

That's the only other thing that I'm seeing as a potential difference.

**Comment by steffenmllr** [comment]
OK I've isolated the case so that it is reproducible and put it here: 
https://github.com/steffenmllr/rquery-issue

The only thing which kind of (might) makes sense it that it is `karma` / `babel` / `webpack` related (which also is weird because calling `TestUtils.Simulate.click` just works fine)

**Comment by percyhanna** [comment]
Hi Steffen,

I haven't had a chance to follow up on this until today. Thanks for providing a small reproducible example, that makes testing a lot easier.

After debugging it locally, my best guess is that it is related to Karma and how React batches its updates. It could also relate to webpack/babel. I didn't get to look in-depth at how React determines which batching strategy to use, but I did find [a discussion about the topic online](https://groups.google.com/forum/#!topic/reactjs/G6pljvpTGX0). The discussion isn't extremely useful, but does seem to imply that batching may be part of the problem.

I would love to provide more assistance, as this is possibly something other users will run into, but at this point I wasn't able to find out much more than that.

**Comment by percyhanna** [comment]
I actually think I might have to blame Babel and/or webpack now. I set up `karma-mocha` in `rquery` and my tests pass fine (except that Sinon spies were broken). See the setup here: https://github.com/percyhanna/rquery/tree/percy/karma_vs_mocha

**Comment by percyhanna** [comment]
I believe it's the same root problem: React's update batching. Not sure how/why Babel/Webpack might have anything to do with that, though.

**Comment by percyhanna** [comment]
So I did some more debugging to find out the absolute cause of the issue, and I did find something that I believe does point to Webpack.

It seems like the root cause is that the `React` module [defined in `component.spec.jsx`](https://github.com/steffenmllr/rquery-issue/blob/master/app/compontent.spec.jsx#L3) is not the same `React` module [passed to `$R`](https://github.com/steffenmllr/rquery-issue/blob/master/tests/globals.js#L12) in `globals.js`.

By making a [slight modification to `rquery.js`](https://github.com/percyhanna/rquery/commit/93216e8606214f776261b6fba2373f800f1f6a8d), I was able to confirm that the two `React` objects were different. Then, by making a [small change to `component.spec.jsx`](https://github.com/percyhanna/rquery-issue/commit/c6862448b2b3624c8fa47c28f76d83c1a7291baa), I made the tests pass.

**Comment by percyhanna** [comment]
It could also be a problem with Karma?
